name: Deploy Django to EC2

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Build Docker Image
        run: |
          docker build -t your_docker_image_name .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag your_docker_image_name "${{ secrets.DOCKER_USERNAME }}/your_docker_image_name:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/your_docker_image_name:latest"

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull the latest Docker image
            docker pull "${{ secrets.DOCKER_USERNAME }}/your_docker_image_name:latest"

            # Stop and remove the existing container if it exists
            docker stop your_container_name || true
            docker rm your_container_name || true

            # Run the new container
            docker run -d --name your_container_name -p 8000:8000 \
              -e DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/your_db_name \
              "${{ secrets.DOCKER_USERNAME }}/your_docker_image_name:latest"
          EOF
